### ISSUE TITLE
Not working on IE 11

### ISSUE THREAD

**Issue by nmcalabroso** [myplanet/angular-deep-blur#2]
I tried the demo using IE 11 and the selection in the dropdown just hides [not selected] when clicked or focused on.

**Comment by nmcalabroso** [comment]
Hi! Just observed the blur event object in IE and apparently `toElement` is not enough anymore. `relatedTarget` is also null just like in firefox (see #1) . The relevant properties are `currentTarget` and `delegateTarget`. They have equal values at my current test (having two anchor tags - focusing and blurring).

My concern is the difference between the two. What should we choose? For now, it's logical to have `currentTarget`. Thoughts? @atesgoral

**Comment by atesgoral** [comment]
Will do some cross-browser testing to see what the current state across all browsers IE8+ is.

**Comment by nmcalabroso** [comment]
:+1:
